version: "3.9"
services:
  hrtracker-api-image:
    image: hrtracker-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: alejandrobravo09
      MYSQL_DATABASE: hr_tracker
      MYSQL_USER: sbravoc
      MYSQL_PASSWORD: 092003
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:

volumes:
  mysql-volume: